<?php

/**
 * BaseEfidiarioCompeticion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $pais_id
 * @property EfidiarioPais $EfidiarioPais
 * 
 * @method string               getName()          Returns the current record's "name" value
 * @method integer              getPaisId()        Returns the current record's "pais_id" value
 * @method EfidiarioPais        getEfidiarioPais() Returns the current record's "EfidiarioPais" value
 * @method EfidiarioCompeticion setName()          Sets the current record's "name" value
 * @method EfidiarioCompeticion setPaisId()        Sets the current record's "pais_id" value
 * @method EfidiarioCompeticion setEfidiarioPais() Sets the current record's "EfidiarioPais" value
 * 
 * @package    efidiario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEfidiarioCompeticion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('efidiario_competicion');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('pais_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EfidiarioPais', array(
             'local' => 'pais_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}