<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/08/23 00:21:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=efidiario',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
