<?php

/**
 * EfidiarioPaisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EfidiarioPaisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EfidiarioPaisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EfidiarioPais');
    }
}