<?php

/**
 * EfidiarioCompeticionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EfidiarioCompeticionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EfidiarioCompeticionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EfidiarioCompeticion');
    }
}