<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/09/03 12:47:39

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=efidiario',
  'username' => 'root',
  'password' => 'colo',
  'name' => 'doctrine',
)),);
