EfidiarioPais:
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(255), notnull: true, unique: true }

EfidiarioCompeticion:
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(255), notnull: true, unique: true }
    pais_id: { type: integer, notnull: true }    
  relations:
    EfidiarioPais: { onDelete: CASCADE, local: pais_id, foreign: id} 
   
 